"""Business/service-layer logic for the Football Auction Manager."""

from .auction_service import (
    AuctionTransactionError,
    TransactionResult,
    budget_reserve_violation_message,
    eligible_for_reauction,
    get_current_player,
    process_sale,
    process_unsold,
    resolved_player_ids,
    sold_player_ids,
    team_can_bid_for_player,
    team_has_goalkeeper,
)
from .auction_session_service import AuctionSession, SessionMode
from .config_service import BrandingConfig, load_branding_config, load_position_colors, load_settings
from .persistence_service import (
    SCHEMA_VERSION,
    PersistenceError,
    SavedSessionSummary,
    archive_live_session,
    atomic_write_json,
    autosave_hook,
    build_snapshot,
    delete_mock_session,
    delete_save_file,
    detect_active_live_session,
    list_mock_sessions,
    load_session,
    restore_session,
    save_session,
    session_save_path,
    summarize_save_file,
)
from .player_service import (
    EXPECTED_AUCTION_ELIGIBLE_COUNT,
    EXPECTED_CAPTAIN_COUNT,
    EXPECTED_TEAM_COUNT,
    EXPECTED_TOTAL_PLAYERS,
    SetupCheck,
    SetupValidationResult,
    filter_players,
    load_players,
    load_teams,
    player_status_label,
    validate_setup,
)
from .randomization_service import (
    EXPECTED_ELIGIBLE_PLAYER_COUNT,
    create_auction,
    create_auction_queue,
)
from .team_service import TeamSummary, build_team_summaries, build_team_summary, load_team_summaries

__all__ = [
    "AuctionSession",
    "AuctionTransactionError",
    "BrandingConfig",
    "EXPECTED_AUCTION_ELIGIBLE_COUNT",
    "EXPECTED_CAPTAIN_COUNT",
    "EXPECTED_ELIGIBLE_PLAYER_COUNT",
    "EXPECTED_TEAM_COUNT",
    "EXPECTED_TOTAL_PLAYERS",
    "PersistenceError",
    "SCHEMA_VERSION",
    "SavedSessionSummary",
    "SessionMode",
    "SetupCheck",
    "SetupValidationResult",
    "TeamSummary",
    "TransactionResult",
    "archive_live_session",
    "atomic_write_json",
    "autosave_hook",
    "budget_reserve_violation_message",
    "build_snapshot",
    "build_team_summaries",
    "build_team_summary",
    "create_auction",
    "create_auction_queue",
    "delete_mock_session",
    "delete_save_file",
    "detect_active_live_session",
    "eligible_for_reauction",
    "filter_players",
    "get_current_player",
    "list_mock_sessions",
    "load_branding_config",
    "load_players",
    "load_position_colors",
    "load_session",
    "load_settings",
    "load_team_summaries",
    "load_teams",
    "player_status_label",
    "process_sale",
    "process_unsold",
    "resolved_player_ids",
    "restore_session",
    "save_session",
    "session_save_path",
    "sold_player_ids",
    "summarize_save_file",
    "team_can_bid_for_player",
    "team_has_goalkeeper",
    "validate_setup",
]
